# Generated by Django 4.1.2 on 2022-10-21 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MyApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='family',
            name='age',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='family',
            name='date',
            field=models.DateField(),
        ),
    ]
